-- MySQL Script generated by MySQL Workbench
-- Mon Apr 13 18:02:41 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sistemaClinica
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sistemaClinica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sistemaClinica` DEFAULT CHARACTER SET utf8 ;
USE `sistemaClinica` ;

-- -----------------------------------------------------
-- Table `sistemaClinica`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemaClinica`.`usuarios` (
  `idUsuarios` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  `nome` VARCHAR(60) NOT NULL,
  `perfil` ENUM('ADMIN', ' FUNCIONARIO') NOT NULL,
  PRIMARY KEY (`idUsuarios`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemaClinica`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemaClinica`.`produtos` (
  `idProdutos` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(70) NOT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  `discricao` VARCHAR(100) NULL,
  `quantidadeEstoque` INT NOT NULL,
  `estoqueMinimo` INT NULL DEFAULT 5,
  PRIMARY KEY (`idProdutos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemaClinica`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemaClinica`.`clientes` (
  `idClientes` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `telefone` VARCHAR(30) NOT NULL,
  `endereco` VARCHAR(45) NULL,
  `email` VARCHAR(100) NULL,
  `dataCadastro` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idClientes`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemaClinica`.`vendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemaClinica`.`vendas` (
  `idVendas` INT NOT NULL AUTO_INCREMENT,
  `data` DATETIME NOT NULL,
  `valorTotal` DECIMAL(10,2) NOT NULL,
  `idClientes` INT NOT NULL,
  `idUsuarios` INT NOT NULL,
  PRIMARY KEY (`idVendas`),
  INDEX `fk_vendas_clientes_idx` (`idClientes` ASC),
  INDEX `fk_vendas_usuarios1_idx` (`idUsuarios` ASC) ,
  CONSTRAINT `fk_vendas_clientes`
    FOREIGN KEY (`idClientes`)
    REFERENCES `sistemaClinica`.`clientes` (`idClientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vendas_usuarios1`
    FOREIGN KEY (`idUsuarios`)
    REFERENCES `sistemaClinica`.`usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemaClinica`.`intens_venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemaClinica`.`intens_venda` (
  `idIntensVenda` INT NOT NULL AUTO_INCREMENT,
  `quantidade` INT NOT NULL,
  `preco_unitario` DECIMAL(10,2) NOT NULL,
  `idVendas` INT NOT NULL,
  `idProdutos` INT NOT NULL,
  PRIMARY KEY (`idIntensVenda`),
  INDEX `fk_intens_venda_vendas1_idx` (`idVendas` ASC) ,
  INDEX `fk_intens_venda_produtos1_idx` (`idProdutos` ASC) ,
  CONSTRAINT `fk_intens_venda_vendas1`
    FOREIGN KEY (`idVendas`)
    REFERENCES `sistemaClinica`.`vendas` (`idVendas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_intens_venda_produtos1`
    FOREIGN KEY (`idProdutos`)
    REFERENCES `sistemaClinica`.`produtos` (`idProdutos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
